//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkBotLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serving
    {
        public int ID { get; set; }
        public System.DateTime Time { get; set; }
        public int User { get; set; }
        public int Recipe { get; set; }
        public decimal Scale { get; set; }
    
        public virtual Recipe Recipe1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
